### ISSUE TITLE
No Refresh

### ISSUE THREAD

**Issue by drfunjohn** [skanehira/denops-docker.vim#9]
- NVIM v0.7.0-dev+835-gf65b0d423
- deno 1.18.0 (release, x86_64-apple-darwin)
   v8 9.8.177.6
   typescript 4.5.2
- OS: macOS 11.6.2 20G314 x86_64

**Scenario**:
When DockeImages or DockerContainers is opened. 
And new docker or container.
Rerun rerun commad DockerImages/DockerContainers.

**Result**: 
Content of buffer is not changed.
After reopen buffer and rerun command does not help.

**W/A:** 

- re-run neovim is required. 
- e: (@skanehira)

**Comment by skanehira** [comment]
@drfunjohn Thank you for reporting.
I'll fix this.
If you want to refresh, please execute `:e` until my fixiing.

**Comment by skanehira** [comment]
@drfunjohn 
Fixed in https://github.com/skanehira/denops-docker.vim/pull/10
Please update and let me know if doesn't work.
